/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mascova.qeela.ui;

import com.mascova.qeela.controller.CustomerLookupController;
import com.mascova.qeela.controller.EmployeeLookupController;
import com.mascova.qeela.controller.SalesDetailController;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author irfan
 */
public class SalesDetail extends InternalFrame {

    public static final int WEIGHT = 470;
    public static final int HEIGHT = 250;
    private SalesDetailController ddc = null;
    private CustomerLookupController clc = null;
    private EmployeeLookupController elc = null;

    /**
     * Creates new form SalesDetail
     */
    public SalesDetail(SalesDetailController ddc, CustomerLookupController clc,
            EmployeeLookupController elc) {
        this.ddc = ddc;
        this.clc = clc;
        this.elc = elc;
        initComponents();
        customerCodLookupControl.setLookupController(clc);
        sellerCodLookupControl.setLookupController(elc);
//        this.setSize(WEIGHT, HEIGHT);  
        this.setResizable(false);

    }

    public Form getMainPanel() {
        return mainPanel;
    }

    private String getValueObjectClassName() {
        return "com.mascova.qeela.entity.Sales";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        copyButton1 = new org.openswing.swing.client.CopyButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        mainPanel = new org.openswing.swing.form.client.Form();
        idNumericControl = new org.openswing.swing.client.NumericControl();
        labelControl6 = new org.openswing.swing.client.LabelControl();
        amountNumericControl = new org.openswing.swing.client.NumericControl();
        customerCodLookupControl = new org.openswing.swing.client.CodLookupControl();
        sellerCodLookupControl = new org.openswing.swing.client.CodLookupControl();
        labelControl7 = new org.openswing.swing.client.LabelControl();
        labelControl8 = new org.openswing.swing.client.LabelControl();
        labelControl9 = new org.openswing.swing.client.LabelControl();

        detailPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel.add(insertButton1);
        buttonsPanel.add(copyButton1);
        buttonsPanel.add(editButton1);
        buttonsPanel.add(reloadButton1);
        buttonsPanel.add(saveButton1);
        buttonsPanel.add(deleteButton1);

        detailPanel.add(buttonsPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setVOClassName(getValueObjectClassName());
        mainPanel.setCopyButton(copyButton1        );
        mainPanel.setDeleteButton(deleteButton1);
        mainPanel.setEditButton(editButton1);
        mainPanel.setFormController(ddc);
        mainPanel.setInsertButton(insertButton1);
        mainPanel.setReloadButton(reloadButton1);
        mainPanel.setSaveButton(saveButton1);

        idNumericControl.setAttributeName("id");
        idNumericControl.setEnabled(false);
        idNumericControl.setEnabledOnEdit(false);
        idNumericControl.setEnabledOnInsert(false);

        labelControl6.setLabel("ID");

        amountNumericControl.setAttributeName("amount");

        customerCodLookupControl.setAttributeName("customer.name");

        sellerCodLookupControl.setAttributeName("seller.name");

        labelControl7.setLabel("Amount");

        labelControl8.setLabel("Customer");

        labelControl9.setLabel("Seller");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelControl6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellerCodLookupControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCodLookupControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountNumericControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumericControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelControl6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumericControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountNumericControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelControl7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerCodLookupControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellerCodLookupControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelControl9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        detailPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(detailPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.NumericControl amountNumericControl;
    private javax.swing.JPanel buttonsPanel;
    private org.openswing.swing.client.CopyButton copyButton1;
    private org.openswing.swing.client.CodLookupControl customerCodLookupControl;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private javax.swing.JPanel detailPanel;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.client.NumericControl idNumericControl;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.client.LabelControl labelControl6;
    private org.openswing.swing.client.LabelControl labelControl7;
    private org.openswing.swing.client.LabelControl labelControl8;
    private org.openswing.swing.client.LabelControl labelControl9;
    private org.openswing.swing.form.client.Form mainPanel;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.client.CodLookupControl sellerCodLookupControl;
    // End of variables declaration//GEN-END:variables
}
